services:
  # Serviço para o backend Flask
  backend:
    build: .
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - backend-network

  # Serviço para o banco de dados SQLite
  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite-db
    volumes:
      - C:/Users/Notbook/Desktop/PUC/Eng. Software/MVP/MVP - Arquitetura de Software/backEnd/server/database/db.sqlite3:/data/db.sqlite3
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge